version: '3.8'
services:
  mysql:
    image: mysql:latest
    container_name: event_mysql
    environment:
      MYSQL_DATABASE: EventCode
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
      MYSQL_ROOT_PASSWORD: mysqlroot
    ports:
      - "3306:3306"
    restart: always
